# ==========================================================================
# VOLATILE LEDGER: 1:1 PARALLEL INTEGRITY MATRICES
# ==========================================================================

# MATRIX A: THE FILE VALIDATION HASH REGISTRY (1:1 with existenzLocations)
existenzHashes = {
    "core": {
        "Core":       "22023c142c21687803a3cdedb82684973d7ab5bb601b2b35d0bd8b448e26f99e",
        "Threat":     "1f95497bb174e069c2b727d8b72a7d556a03c0db451dcf2bac6b00bf191291ca",
        "Signatures": "VALID_SHA256_OF_THE_SEALED_SIGNING_FILE_HERE",
        "Check":      "b36d1e03858491d3b12ddd1f4f3043458be6065befb6f25622475b8bc909fd85",
        "Cores":      "bb11656cb916db4245e1ac23cf9b04f03fddcc492faf420e9d0ecf54e4384af8"
    },
    "manifest": {
        "dist":   "COMPUTED_DIR_HASH_OR_BLANK",
        "tools":  "COMPUTED_DIR_HASH_OR_BLANK",
        "build":  "COMPUTED_DIR_HASH_OR_BLANK",
        "master": "COMPUTED_DIR_HASH_OR_BLANK"
    },
    "sign": {
        "engineStruct":   "COMPUTED_HASH_HERE",
        "engineLibrary":  "COMPUTED_HASH_HERE",
        "engineData":     "COMPUTED_HASH_HERE",
        "structures":     "COMPUTED_HASH_HERE",
        "jsonConfig":     "COMPUTED_HASH_HERE",
        "jsonSignatures": "COMPUTED_HASH_HERE",
        "jsonData":       "COMPUTED_HASH_HERE",
        "jsonManifest":   "COMPUTED_HASH_HERE",
        "jsonLocalConf":  "COMPUTED_HASH_HERE"
    }
}

# MATRIX B: THE PRIVATE KEY SIGNATURE REGISTRY (1:1 with existenzLocations)
# Stores colon-delimited (:) multi-sig streams generated by your key ceremonies
existenzSignatures = {
    "core": {
        "Core":       "PLATFORM_SIG_HEX:DEVELOPER_SIG_HEX:PERSONAL_SIG_HEX",
        "Threat":     "PLATFORM_SIG_HEX:DEVELOPER_SIG_HEX:PERSONAL_SIG_HEX",
        "Signatures": "PLATFORM_SIG_HEX:DEVELOPER_SIG_HEX:PERSONAL_SIG_HEX",
        "Check":      "PLATFORM_SIG_HEX:DEVELOPER_SIG_HEX",
        "Cores":      "PLATFORM_SIG_HEX:DEVELOPER_SIG_HEX"
    },
    "manifest": {
        "dist":   "ENVIRONMENT_SIG_HEX",
        "tools":  "ENVIRONMENT_SIG_HEX",
        "build":  "DEVELOPER_SIG_HEX:PERSONAL_SIG_HEX",
        "master": "DEVELOPER_SIG_HEX:PERSONAL_SIG_HEX"
    },
    "sign": {
        "engineStruct":   "DEVELOPER_SIG_HEX",
        "engineLibrary":  "DEVELOPER_SIG_HEX",
        "engineData":     "DEVELOPER_SIG_HEX",
        "structures":     "DEVELOPER_SIG_HEX",
        "jsonConfig":     "DEVELOPER_SIG_HEX",
        "jsonSignatures": "DEVELOPER_SIG_HEX",
        "jsonData":       "DEVELOPER_SIG_HEX",
        "jsonManifest":   "DEVELOPER_SIG_HEX",
        "jsonLocalConf":  "DEVELOPER_SIG_HEX"
    }
}
