// AUTOMATICALLY GENERATED BY EXISTENZ BUILD PIPELINE
// Version: 0.76-PoC | Power Profile: < 1uW (Sub-Microwatt)

const ExistentialCore = {
    EXISTENCE: 1 << 0,
    AUTONOMY: 1 << 1,
    INTEGRITY: 1 << 2,
    PSYCHOLOGY: 1 << 3,
    PHYSICAL: 1 << 4,
    DISABILITY: 1 << 5,
    DEVELOPMENT: 1 << 6,
    PROPERTY: 1 << 7,
    PRESENCE: 1 << 8,
};
export default ExistentialCore;
