// AUTOMATICALLY GENERATED BY EXISTENZ BUILD PIPELINE
// Version: 0.76-PoC | Power Profile: < 1uW (Sub-Microwatt)

#pragma once
#include <cstdint>

namespace Existenz {
    const uint64_t EXISTENCE = 1ULL << 0;
    const uint64_t AUTONOMY = 1ULL << 1;
    const uint64_t INTEGRITY = 1ULL << 2;
    const uint64_t PSYCHOLOGY = 1ULL << 3;
    const uint64_t PHYSICAL = 1ULL << 4;
    const uint64_t DISABILITY = 1ULL << 5;
    const uint64_t DEVELOPMENT = 1ULL << 6;
    const uint64_t PROPERTY = 1ULL << 7;
    const uint64_t PRESENCE = 1ULL << 8;
}
