# ==========================================================================
# THE EXISTENZ PLATFORM (IMMUTABLE SIGNATURES)
# GENERATED BY THE COMPILER SUITE. DO NOT HAND-EDIT THIS WORKSPACE.
# ==========================================================================
# FILE: existenzStruct/master/existentialCoreSignatures.py
#
existentialCoreCheckMagic                    = b"EX25IMMUT32CORE7617"
existentialCoreCheckSignatures               = "ad387f3945de2105da6d4484bc871ef494dbd424bc871ef494dbd425da6d4484"

class existentialCoreSignatures:
    """Master repository vault consolidating all 256-bit immutable platform layer signatures."""
    # 1. Core Pillars Layer (existentialCore.py)
    existentialCoreSignature                     = "22023c142c21687803a3cdedb82684973d7ab5bb601b2b35d0bd8b448e26f99e"
    # 2. Threat & Canary Layers (existentialCoreThreat.py)
    existentialCoreThreatSignature               = "57c413f8531731df0d2f09a260ea36c7e49269348b553fdeeaa2dd11e7bc4bb9"
    existentialCoreThreatLegalSignature          = "6d07d97272d414f966ea7a9d7b2956b96541fecbcb9079f375408a62b3b6bd6e"
    existentialCoreThreatStructuresSignature     = "759533dfd2a276046bc62985b17df7cefb999a1c3a07b7b983e5ee278d80302d"
    # 3. Macro Platform Check Layer (existentialCoreCheck.py)
    existentialCoreCheckSignature                = "7c165b322566e304975917cdc92de03d3ab14e72d1edaefc2ea18f7444ac891c"
    
