import os
import sys
import json
import hashlib

# 8 Main Languages/Modes mapping
LANGUAGES = [
    "C++", "JAVASCRIPT", "PERL", "PYTHON MODULE/LIBRARY", 
    "PYTHON", "XML", "JSON", "AI_QUESTION"
]

def parse_controller_flags():
    """
    Simulates parsing your 8-bit / Multi-Register Controller configuration.
    Customize the values here or read them dynamically from a local configuration file.
    """
    return {
        # Select active languages using an 8-bit mask (e.g., 0b01110011 -> C++, JS, Python, XML)
        "language_mask": 0b01110011, 
        # Export mode: 1=export_mini, 2=export_small, 4=export_detailed, 8=export_library
        "export_mode": 4,             
        # Checksum mode: 1=verify, 2=calculate, 4=warn, 8=replace
        "checksum_mode": 2            
    }

def compile_matrix():
    flags = parse_controller_flags()
    out_dir = "generated_outputs"
    os.makedirs(out_dir, exist_ok=True)
    
    print(f"--- Launching Existenz Matrix Ingestion Engine v0.76-PoC ---")
    print(f"Active Language Mask: {bin(flags['language_mask'])}")
    print(f"Target Mode: {flags['export_mode']} | Checksum Rule: {flags['checksum_mode']}\n")
    
    # Core system data parsed from your uploaded chunks
    core_data = {
        "version": "0.76-PoC",
        "poweruse": "< 1uW (Sub-Microwatt)",
        "pillars": ["EXISTENCE", "AUTONOMY", "INTEGRITY", "PSYCHOLOGY", "PHYSICAL", "DISABILITY", "DEVELOPMENT", "PROPERTY", "PRESENCE"]
    }
    
    for idx, lang in enumerate(LANGUAGES):
        # Evaluate if the specific language bit is high
        if flags["language_mask"] & (1 << idx):
            ext = lang.split()[0].lower().replace("+", "p")
            output_file = os.path.join(out_dir, f"existenz_core.{ext}")
            print(f"Generating system structures for: {lang} -> {output_file}")
            
            with open(output_file, "w", encoding="utf-8") as out:
                out.write(f"// AUTOMATICALLY GENERATED BY EXISTENZ BUILD PIPELINE\n")
                out.write(f"// Version: {core_data['version']} | Power Profile: {core_data['poweruse']}\n\n")
                
                if ext == "json":
                    out.write(json.dumps(core_data, indent=4))
                elif ext == "cpp":
                    out.write("#pragma once\n#include <cstdint>\n\nnamespace Existenz {\n")
                    for bit_idx, pillar in enumerate(core_data["pillars"]):
                        out.write(f"    const uint64_t {pillar} = 1ULL << {bit_idx};\n")
                    out.write("}\n")
                elif ext == "javascript":
                    out.write("const ExistentialCore = {\n")
                    for bit_idx, pillar in enumerate(core_data["pillars"]):
                        out.write(f"    {pillar}: 1 << {bit_idx},\n")
                    out.write("};\nexport default ExistentialCore;\n")
                else:
                    out.write(f"# Framework mappings for layout language: {lang}\n")
            
            # Execute Checksum Logic Routine if required
            if flags["checksum_mode"] == 2:
                with open(output_file, "rb") as f:
                    file_hash = hashlib.sha256(f.read()).hexdigest()
                print(f"  [Integrity Check] Calculated SHA-256: {file_hash}")

if __name__ == "__main__":
    compile_matrix()
