# ==========================================================================
# EXISTENZ Plugin Compiler: C++ (C++17 / C++20 Header Archetypes)
# ==========================================================================
import os
from master_build_tools.engineResultLibrary import flush_build_artifact

def compile_structures(repo_root: str, structures: dict, error_handler):
    """Compiles all loose structures programmatically with comment strings next to every single bit."""
    for name, tokens in structures.items():
        lines = [
            f"// Automatically generated by Existenz AST Engine. Do not modify.",
            f"#pragma once",
            f"#include <cstdint>",
            f"",
            f"namespace existenz {{",
            f"    enum class {name} : uint64_t {{"
        ]
        
        for token_name, bit_val in tokens:
            # Render clean bitwise descriptions adjacent to structural rows natively
            comment_marker = f"// Bit Flag Weight: {bit_val}"
            lines.append(f"        {token_name:<32} = {bit_val},".ljust(64) + comment_marker)
            
        lines.extend([
            f"    }};",
            f"}} // namespace existenz"
        ])
        
        # Saves directly to loose format: dist/cpp/<StructureName>.hpp
        flush_build_artifact(repo_root, "cpp", f"{name}.hpp", "\n".join(lines), error_handler)

def inject_fetch_logic(repo_root: str, error_handler):
    """Injects 2 distinct, native ways to query the global existentialCores.json registry asset."""
    fetch_snippets = """// Automatically generated fetch logic options.
#pragma once
#include <string>
#include <fstream>
#include <sstream>

namespace existenz::fetch {
    // APPROACH 1: Native Filesystem Stream Read (Local Context)
    inline std::string fetch_cores_via_fs(const std::string& path = "dist/existentialCores.json") {
        std::ifstream file(path);
        if (!file.is_open()) return "";
        std::stringstream buffer;
        buffer << file.rdbuf();
        return buffer.str();
    }

    // APPROACH 2: Dynamic Pipeline Memory Buffer Stub (Supply-Chain Isolated)
    inline const char* fetch_cores_embedded_stub() {
        return "{\\"existentialToken\\": {\\"status\\": \\"verified\\"}}";
    }
}
"""
    flush_build_artifact(repo_root, "cpp", "existentialFetchLogic.hpp", fetch_snippets, error_handler)
