# ==========================================================================
# EXISTENZ Plugin Compiler: Rust (Type-Safe Modules)
# ==========================================================================
import os
from master_build_tools.engineResultLibrary import flush_build_artifact

def compile_structures(repo_root: str, structures: dict, error_handler):
    """Compiles reflected structures into type-safe loose Rust code blocks."""
    for name, tokens in structures.items():
        lines = [
            f"// Automatically generated by Existenz AST Engine. Do not modify.",
            f"#[allow(non_camel_case_types)]",
            f"pub enum {name} {{"
        ]
        for token_name, bit_val in tokens:
            lines.append(f"    {token_name} = {bit_val}, // Weight status: {hex(bit_val)}")
        lines.append("}")
        
        flush_build_artifact(repo_root, "rust", f"{name}.rs", "\n".join(lines), error_handler)

def inject_fetch_logic(repo_root: str, error_handler):
    """Injects 2 distinct native ways to stream the manifest file inside your Rust targets."""
    fetch_snippets = """// Native retrieval approaches for existentialCores.json
use std::fs::File;
use std::io::Read;

// METHOD 1: Direct File Stream Ingestion
pub fn fetch_cores_from_file() -> Result<String, std::io::Error> {
    let mut file = File::open("dist/existentialCores.json")?;
    let mut contents = String::new();
    file.read_to_string(&mut contents)?;
    Ok(contents)
}

// METHOD 2: Compile-Time Embedded Macro Include
pub const EMBEDDED_CORES_BLUEPRINT: &str = include_str!("../existentialCores.json");
"""
    flush_build_artifact(repo_root, "rust", "fetch_logic.rs", fetch_snippets, error_handler)
