# ==========================================================================
# EXISTENZ Plugin Compiler: TypeScript (Strict Immutable Node/Browser Assets)
# ==========================================================================
import os
from master_build_tools.engineBuilderLibrary import flush_build_artifact

def compile_structures(repo_root: str, structures: dict, error_handler):
    """Compiles reflected metadata tokens into type-safe immutable TypeScript definitions."""
    for name, tokens in structures.items():
        lines = [
            f"// Automatically generated by Existenz AST Engine. Do not modify.",
            f"export namespace {name} {{"
        ]
        
        for token_name, bit_val in tokens:
            # Enforce inline line comments documenting flag bit weights
            comment_marker = f"// Bit Flag Weight: {bit_val}"
            lines.append(f"    export const {token_name}: number = {bit_val};".ljust(64) + comment_marker)
            
        lines.extend([
            f"}}",
            f"",
            f"// Type-safe matching element boundary check map asset representation",
            f"export type {name}Type = typeof {name}[keyof typeof {name}];"
        ])
        
        # Flushes directly into individual loose files: dist/typescript/<StructureName>.ts
        flush_build_artifact(repo_root, "typescript", f"{name}.ts", "\n".join(lines), error_handler)

def inject_fetch_logic(repo_root: str, error_handler):
    """Injects 2 distinct native ways to ingest existentialCores.json inside target applications."""
    fetch_snippets = """// Automatically generated fetch logic utilities for existentialCores.json
import * as fs from 'fs';
import * as path from 'path';

export namespace ExistenzCoresFetch {
    // APPROACH 1: Synchronous Filesystem Ingestion (Block-Safe Local Run)
    export function fetchCoresSync(customPath?: string): string {
        const targetPath = customPath || path.resolve(__dirname, '../existentialCores.json');
        if (!fs.existsSync(targetPath)) return '';
        return fs.readFileSync(targetPath, 'utf-8');
    }

    // APPROACH 2: Asymmetric Promise-Driven Stream Read (Async I/O Non-Blocking)
    export function fetchCoresAsync(customPath?: string): Promise<string> {
        const targetPath = customPath || path.resolve(__dirname, '../existentialCores.json');
        return new Promise((resolve) => {
            fs.readFile(targetPath, 'utf-8', (err, data) => {
                if (err) return resolve('');
                resolve(data);
            });
        });
    }
}
"""
    flush_build_artifact(repo_root, "typescript", "existentialFetchLogic.ts", fetch_snippets, error_handler)
