# ==========================================================================
# EXISTENZ CORE BUILDER (Signing Suite & Cross-Compiler)
# Version: v0.76.16 | Github Deployment
# Copyright (c) 2026 by Gunther Voet. All Rights Reserved.
# Released under strict Non-Commercial Open-Source License terms.
# ==========================================================================

# Auto-generated Operational Controller State Stub for cliStateBuild 
# ==========================================================================
# EXISTENZ  master/struct/module/cliStateBuild.py
# Universal Reflection Cross-Language Artifact Compiler Engine
# Copyright (c) 2026 by Gunther Voet. All Rights Reserved.
# Released under strict Non-Commercial Open-Source License terms.
# ==========================================================================
import os
import json
import inspect
from enum import IntFlag
from engineSigningMeta import existenzLocations

def extract_intflag_tokens(flag_class) -> list:
    """Dynamically reflects over an IntFlag class to extract type-safe names and values."""
    if not issubclass(flag_class, IntFlag):
        return []
    # Sort by raw numeric bitweight value to preserve your chronological execution timelines
    return sorted(
        [(name, int(value)) for name, value in flag_class.__members__.items()],
        key=lambda x: x[1]
    )

def compile_to_cpp(class_name: str, tokens: list, signature_hex: str = "") -> str:
    """Compiles reflected tokens into a modern, type-safe C++ modern enum class structure."""
    lines = [
        f"// Automatically generated by Existenz Build Engine. Do not edit manually.",
        f"#pragma once",
        f"#include <cstdint>",
        f"",
        f"namespace existenz {{",
        f"    enum class {class_name} : uint64_t {{"
    ]
    for name, val in tokens:
        lines.append(f"        {name:<24} = {val}," )
    lines.extend([
        f"    }};",
        f""
    ])
    if signature_hex:
        lines.append(f'    const char* const {class_name}_SIGNATURE = "{signature_hex}";')
    lines.append(f"}} // namespace existenz")
    return "\n".join(lines)

def compile_to_rust(class_name: str, tokens: list, signature_hex: str = "") -> str:
    """Compiles reflected tokens into a native, bitflags-compatible Rust module."""
    lines = [
        f"// Automatically generated by Existenz Build Engine. Do not edit manually.",
        f"#[allow(non_camel_case_types)]",
        f"pub enum {class_name} {{"
    ]
    for name, val in tokens:
        lines.append(f"    {name} = {val},")
    lines.extend([
        f"}}",
        f""
    ])
    if signature_hex:
        lines.append(f'pub const {class_name.upper()}_SIGNATURE: &str = "{signature_hex}";')
    return "\n".join(lines)

def compile_to_go(class_name: str, tokens: list, signature_hex: str = "") -> str:
    """Compiles reflected tokens into clean, type-safe idiomatic Go constant structures."""
    lines = [
        f"// Automatically generated by Existenz Build Engine. Do not edit manually.",
        f"package existenz",
        f"",
        f"type {class_name} uint64",
        f"",
        f"const ("
    ]
    for name, val in tokens:
        lines.append(f"    {class_name}_{name:<24} {class_name} = {val}")
    lines.extend([
        f")",
        f""
    ])
    if signature_hex:
        lines.append(f'const {class_name}Signature = "{signature_hex}"')
    return "\n".join(lines)


def execute(args, error_handler, repo_root: str):
    """
    Executes universal cross-compilation loops.
    Reflects live memory data definitions out to native files, bypassing clunky text templates.
    """
    error_handler.print("Initiating reflection-driven multi-language asset compilation...", level="notice")
    
    # 1. Ingest your compiled signature databases to bake constants directly into targets
    json_signatures_path = os.path.abspath(os.path.join(repo_root, existenzLocations["core"]["SignaturesJson"]))
    sig_database = {}
    if os.path.exists(json_signatures_path):
        try:
            with open(json_signatures_path, "r", encoding="utf-8") as js_in:
                sig_database = json.load(js_in).get("existentialToken", {})
        except Exception:
            pass

    # 2. Register the list of your target IntFlag classes to build dynamically
    from engineSigningStruct import existenzSteps, existenzIntegrityKeyStatus, existenzIntegrityKeysHandler
    
    targets_blueprint = [
        ("existenzSteps",              existenzSteps,              sig_database.get("CoreChain_hash", "")),
        ("existenzIntegrityKeyStatus",  existenzIntegrityKeyStatus,  sig_database.get("MagicCheck_hash", "")),
        ("existenzIntegrityKeysHandler", existenzIntegrityKeysHandler, sig_database.get("CoreCheck_hash", ""))
    ]

    # Resolve output directory target boundaries
    build_dir = os.path.abspath(os.path.join(repo_root, "master/build-tools/compiled"))
    os.makedirs(build_dir, exist_ok=True)

    # 3. RUN THE COMPILER LOOPS: Transform live structures to foreign assets programmatically
    for class_name, flag_class, associated_sig in targets_blueprint:
        tokens_list = extract_intflag_tokens(flag_class)
        if not tokens_list:
            continue
            
        error_handler.print(f" [+] Reflecting structural properties for target: [{class_name}]", level="info")

        # Compile matching code representations on the fly
        cpp_code  = compile_to_cpp(class_name, tokens_list, associated_sig)
        rust_code = compile_to_rust(class_name, tokens_list, associated_sig)
        go_code   = compile_to_go(class_name, tokens_list, associated_sig)

        if str(args.run).strip().lower() != "dry":
            try:
                # Flush clean compiler files straight down to disk destinations
                with open(os.path.join(build_dir, f"{class_name}.hpp"), "w", encoding="utf-8") as out_cpp:
                    out_cpp.write(cpp_code)
                with open(os.path.join(build_dir, f"{class_name}.rs"), "w", encoding="utf-8") as out_rs:
                    out_rs.write(rust_code)
                with open(os.path.join(build_dir, f"{class_name}.go"), "w", encoding="utf-8") as out_go:
                    out_go.write(go_code)
                    
                error_handler.print(f"     ➔ Cross-language artifacts compiled successfully: [{class_name}]", level="notice")
            except Exception as io_err:
                error_handler.print(f"Failed writing target build artifact for {class_name}: {io_err}", level="error", exit_code=32)

    error_handler.print("[+++] SUCCESS: Full distribution build phase completed flawless. Workspace is finalized.", level="notice")
